accentKeyboard.layouts['turkish'] = [
  { d: 'q', u: '1' }, //Row 1
  { d: 'w', u: '2' },
  { d: 'e', u: '3' },
  { d: 'r', u: '4' },
  { d: 't', u: '5' },
  { d: 'y', u: '6' },
  { d: 'u', u: '7' },
  { d: 'ı', u: 'I' },
  { d: 'o', u: 'O' },
  { d: 'a', u: 'A' },
  { d: 's', u: 'S' },  //Row 2
  { d: 'd', u: 'D' },
  { d: 'f', u: 'F' },
  { d: 'g', u: 'G' },
  { d: 'h', u: 'H' },
  { d: 'j', u: 'J' },
  { d: 'k', u: 'K' },
  { d: 'l', u: 'L' },
  { d: 'p', u: 'P' },
  { d: 'ğ', u: 'Ğ' },
  { d: 'ü', u: 'Ü' }, //Row 3
  { d: 'ş', u: 'Ş' },
  { d: 'i', u: 'İ' },
  { d: 'â', u: 'Â' },
  { d: 'ö', u: 'Ö' },
  { d: 'ç', u: 'Ç' },
  { d: 'û', u: 'Û' },
  { d: 'z', u: 'Z' },
  { d: 'x', u: 'X' },
  {keyType:"DELETE"},
  {keyType:"CAPS", css:'font-double'},//Row 4
  { d: 'z', u: 'Z' },
  { d: 'x', u: 'X' },
  { d: 'c', u: 'C' },
  { d: 'v', u: 'V' },
  { d: 'b', u: 'B' },
  { d: 'n', u: 'N' },
  { d: 'm', u: 'M' },
  {keyType:"ENTER", css:'key-span-2 font-double'},
  {keyType:"CLEAR_TEXT"},
  {keyType:"SPACE", css:'space gray-key'},
  {keyType:"SWITCH_LANG"} 
];
