accentKeyboard.layouts['english'] = [
  { d: '1', u: '!' }, //Row 1
  { d: '2', u: '@' },
  { d: '3', u: '#' },
  { d: '4', u: '$' },
  { d: '5', u: '%' },
  { d: '6', u: '^' },
  { d: '7', u: '&' },
  { d: '8', u: '*' },
  { d: '9', u: '(' },
  { d: '0', u: ')' },
  { d: 'q', u: 'Q' },  //Row 2
  { d: 'w', u: 'W' },
  { d: 'e', u: 'E' },
  { d: 'r', u: 'R' },
  { d: 't', u: 'T' },
  { d: 'y', u: 'Y' },
  { d: 'u', u: 'U' },
  { d: 'i', u: 'I' },
  { d: 'o', u: 'O' },
  { d: 'p', u: 'P' },
  { d: 'a', u: 'A' },  //Row 3
  { d: 's', u: 'S' },
  { d: 'd', u: 'D' },
  { d: 'f', u: 'F' },
  { d: 'g', u: 'G' },
  { d: 'h', u: 'H' },
  { d: 'j', u: 'J' },
  { d: 'k', u: 'K' },
  { d: 'l', u: 'L' },
  {keyType:"DELETE"},
  {keyType:"CAPS", css:'font-double'},//Row 4
  { d: 'z', u: 'Z' },
  { d: 'x', u: 'X' },
  { d: 'c', u: 'C' },
  { d: 'v', u: 'V' },
  { d: 'b', u: 'B' },
  { d: 'n', u: 'N' },
  { d: 'm', u: 'M' },
  {keyType:"ENTER", css:'key-span-2 font-double'},
  {keyType:"SETTINGS"},
  {keyType:"CLEAR_TEXT"},
  {keyType:"SPACE", css:'key-span-6 gray-key'},
  {keyType:"SWITCH_LANG", css:'key-span-2'} 
];
